{
 "title": "Optics Demo - ZR+ 400G link",
 "tags": [ "demo" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host1_coherent_controller",
    "query": "show tag values from \"gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info\" with key=\"controller_name\" where \"host_name\" =~ /^$host1/"
   },
   {
    "name": "host1_optical_controller",
    "query": "show tag values from \"gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info\" with key=\"name\"  where \"host_name\" =~ /^$host1/"
   },
   {
    "name": "host1",
    "query": "show tag values from \"gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info\" with key=\"host_name\""
   },
   {
    "name": "host2_optics_controller",
    "query": "show tag values from \"gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info\" with key=\"name\" where \"host_name\" =~ /^$host2/"
   },
   {
    "name": "host2_coherent_controller",
    "query": "show tag values from \"gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info\" with key=\"controller_name\" where \"host_name\" =~ /^$host2/"
   },
   {
    "name": "host1_interface",
    "label": "Roma-30 Interface",
    "query": "show tag values from \"gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info\" with key=\"name\"  where \"host_name\" =~ /^$host1/"
   },
   {
    "name": "host2_interface",
    "label": "Battipaglia-54 Interface",
    "query": "show tag values from \"gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info\" with key=\"name\"  where \"host_name\" =~ /^$host2/"
   },
   { "name": "Optics_prefix", "query": "Optics" },
   { "name": "CoherentDSP_prefix", "query": "CoherentDSP" },
   {
    "name": "host2",
    "query": "show tag values from \"gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info\" with key=\"host_name\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center;padding:10px 0\">\n    <span style=\"color:#DEB6F2;font-family:Roboto;font-size:20pt;font-weight:500\">${host1} | Controller: ${CoherentDSP_prefix}${host1_interface}</span>\n</p>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Optics Info: SN | PID | Vendor",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       {
        "params": [
         "transceiver_info/optics_serial_no"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    },
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "transceiver_info/optics_pid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    },
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "transceiver_info/vendor_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$host1_coherent_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Wavelength",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "nm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "dwdm_carrier_wavelength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "OSNR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "optical_signal_to_noise_ratio" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "lane_data/transmit_power" ], "type": "field" },
       { "params": [ "*0.01" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Pre-FEC BER",
   "type": "stat",
   "description": "Bit Error Rate Before Forward Error Correction",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info",
     "select": [
      [
       { "params": [ "otu_fec_satistics/pre_fec_ber" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$host1_coherent_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Q-Factor / Q-Margin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Q-Factor dB",
     "measurement": "gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info",
     "select": [
      [
       { "params": [ "qfactor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$host1_coherent_controller$/" }
     ]
    },
    {
     "alias": "Q-Margin dB",
     "measurement": "gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info",
     "select": [
      [
       { "params": [ "qmargin" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$host1_coherent_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Laser State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "laser_state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Modulation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "modulation_type" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "THz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "dwdm_carrier_frequency" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "lane_data/receive_power" ], "type": "field" },
       { "params": [ "*0.01" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host1_optical_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Post-FEC BER",
   "type": "stat",
   "description": "Bit Error Rate After Forward Error Correction",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info",
     "select": [
      [
       { "params": [ "otu_fec_satistics/post_fec_ber" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host1$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$host1_coherent_controller$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<p style=\"text-align:center;padding:10px 0\">\n    <span style=\"color:#2E7D08;font-family:Roboto;font-size:20pt;font-weight:500\">${host2} | Controller: ${CoherentDSP_prefix}${host2_interface}</span>\n</p>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Optics Info: SN | PID | Vendor",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "1",
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "query": "SELECT last(\"transceiver_info/optics_serial_no\") FROM \"gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"host_name\" =~ /^$zrplus_demo_host2$/ AND \"name\" =~ /^$dco_demo_host2_optics_contr$/) AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "transceiver_info/optics_serial_no"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    },
    {
     "alias": "1",
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "transceiver_info/optics_pid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    },
    {
     "alias": "1",
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "transceiver_info/vendor_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$host2_coherent_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Wavelength",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "nm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "dwdm_carrier_wavelength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "OSNR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "optical_signal_to_noise_ratio" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "lane_data/transmit_power" ], "type": "field" },
       { "params": [ "*0.01" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Pre-FEC BER",
   "type": "stat",
   "description": "Bit Error Rate Before Forward Error Correction",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info",
     "select": [
      [
       { "params": [ "otu_fec_satistics/pre_fec_ber" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$host2_coherent_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Q-Factor / Q-Margin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Q-Factor dB",
     "measurement": "gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info",
     "select": [
      [
       { "params": [ "qfactor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$host2_coherent_controller$/" }
     ]
    },
    {
     "alias": "Q-Margin dB",
     "measurement": "gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info",
     "select": [
      [
       { "params": [ "qmargin" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$host2_coherent_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Laser State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "laser_state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Modulation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "modulation_type" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "THz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "dwdm_carrier_frequency" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "lane_data/receive_power" ], "type": "field" },
       { "params": [ "*0.01" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$host2_optics_controller$/" }
     ]
    }
   ]
  },
  {
   "title": "Post-FEC BER",
   "type": "stat",
   "description": "Bit Error Rate After Forward Error Correction",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gNMI-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info",
     "select": [
      [
       { "params": [ "otu_fec_satistics/post_fec_ber" ], "type": "field" },
       { "params": [ "*100000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host2$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$host2_coherent_controller$/" }
     ]
    }
   ]
  }
 ]
}